#include "src/game/envfx_snow.h"

const GeoLayout prince_valley_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 0, 0, -5600),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 2475, 1085, 5127, 0, 91, 0, prince_valley_dl_cloud_tree_002_mesh_layer_1),
			GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 4244, 4465, 9879, 11, -94, 23, prince_valley_dl_cloud_tree_002_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 0, 0, -5600),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 0, 0, -5600),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_NODE(LAYER_OPAQUE, 3847, 0, 18525),
			GEO_OPEN_NODE(),
				GEO_SHADOW(1, 255, 100),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, prince_valley_dl_terrain_mesh_layer_1),
					GEO_DISPLAY_LIST(LAYER_ALPHA, prince_valley_dl_terrain_mesh_layer_4),
					GEO_DISPLAY_LIST(LAYER_ALPHA, prince_valley_dl_final_revert_mesh_layer_4),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, prince_valley_dl_final_revert_mesh_layer_1),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 0, 0, 5616, prince_valley_dl_zone_water_lake_1_mesh_layer_5),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, prince_valley_dl_final_revert_mesh_layer_5),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -100, 300, -5504),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 0, 0, -5600),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 0, 0, -5600),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout prince_valley_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_OCEAN_SKY, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, -3847, 0, -12925, -3847, -100, -12925, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, prince_valley_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
