#include "src/game/envfx_snow.h"

const GeoLayout welkit_castle_past_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -2, -292, 2762, 0, 90, 0),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -1689, 539, 3555),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 1689, 539, 3555, 0, -180, 0),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -484, 539, 8645, 0, 90, 0),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, welkit_castle_past_dl_geo_arch_stairs_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, welkit_castle_past_dl_geo_entrance_base_level_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, welkit_castle_past_dl_geo_side_arches_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -2, 502, 5283, welkit_castle_past_dl_geo_wellwa_statue_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, welkit_castle_past_dl_final_revert_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -144, -158, 4452),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout welkit_castle_past_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_OCEAN_SKY, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, welkit_castle_past_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
