extern const GeoLayout welkit_castle_past_area_1_geo[];
extern const GeoLayout welkit_castle_past_area_1[];
extern const Collision welkit_castle_past_area_1_collision[];
extern const MacroObject welkit_castle_past_area_1_macro_objs[];
extern Vtx welkit_castle_past_dl_Cube_001_mesh_layer_1_vtx_cull[8];
extern Vtx welkit_castle_past_dl_Cube_001_mesh_layer_1_vtx_0[262];
extern Gfx welkit_castle_past_dl_Cube_001_mesh_layer_1_tri_0[];
extern Gfx mat_welkit_castle_past_dl_f3dlite_material[];
extern Gfx mat_revert_welkit_castle_past_dl_f3dlite_material[];
extern Gfx welkit_castle_past_dl_Cube_001_mesh_layer_1[];
extern Gfx welkit_castle_past_dl_final_revert_mesh_layer_1[];
