extern const GeoLayout gym_area_1_geo[];
extern const GeoLayout gym_area_1[];
extern const Collision gym_area_1_collision[];
extern const MacroObject gym_area_1_macro_objs[];
extern u8 gym_dl_t_0_grass_ci8[];
extern u8 gym_dl_t_0_grass_pal_rgba16[];
extern u8 gym_dl_t_0_rockyhillside_ci8[];
extern u8 gym_dl_t_0_rockyhillside_pal_rgba16[];
extern Vtx gym_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx gym_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx gym_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx gym_dl_platform_mesh_layer_1_vtx_cull[8];
extern Vtx gym_dl_platform_mesh_layer_1_vtx_0[4];
extern Gfx gym_dl_platform_mesh_layer_1_tri_0[];
extern Vtx gym_dl_platform_mesh_layer_1_vtx_1[20];
extern Gfx gym_dl_platform_mesh_layer_1_tri_1[];
extern Gfx mat_gym_dl_mat_white[];
extern Gfx mat_revert_gym_dl_mat_white[];
extern Gfx mat_gym_dl_mat_stonebricks[];
extern Gfx mat_revert_gym_dl_mat_stonebricks[];
extern Gfx mat_gym_dl_mat_rockyhillside[];
extern Gfx mat_revert_gym_dl_mat_rockyhillside[];
extern Gfx gym_dl_Cube_mesh_layer_1[];
extern Gfx gym_dl_platform_mesh_layer_1[];
extern Gfx gym_dl_final_revert_mesh_layer_1[];
